// utils/seoKeywords.ts
export const SEO_SUB_TOPICS = [
  // === DIGITAL MARKETING SPACE ===
  { slug: "free-backlink-sites-list-2026", label: "Free Backlink Sites List 2026", parentSpace: "Digital Marketing" },
  { slug: "high-da-guest-posting-sites-list", label: "High DA Guest Posting Sites List", parentSpace: "Digital Marketing" },
  { slug: "instant-approval-forum-posting-sites", label: "Instant Approval Forum Posting Sites", parentSpace: "Digital Marketing" },
  { slug: "free-dofollow-link-submission-websites", label: "Free Dofollow Link Submission Websites", parentSpace: "Digital Marketing" },
  { slug: "best-web-2-0-sites-for-backlinks", label: "Best Web 2.0 Sites for Backlinks", parentSpace: "Digital Marketing" },
  { slug: "high-dr-profile-creation-sites-list", label: "High DR Profile Creation Sites List", parentSpace: "Digital Marketing" },
  { slug: "instant-indexing-article-publishing-sites", label: "Instant Indexing Article Publishing Sites", parentSpace: "Digital Marketing" },
  { slug: "dofollow-forum-list-free-download", label: "Dofollow Forum List Free Download", parentSpace: "Digital Marketing" },
  { slug: "automated-link-building-sites-platform", label: "Automated Link Building Sites Platform", parentSpace: "Digital Marketing" },
  { slug: "guest-blogging-sites-with-free-traffic", label: "Guest Blogging Sites with Free Traffic", parentSpace: "Digital Marketing" },
  { slug: "niche-relevant-blog-posting-options", label: "Niche Relevant Blog Posting Options", parentSpace: "Digital Marketing" },
  { slug: "free-social-bookmarking-site-directory", label: "Free Social Bookmarking Site Directory", parentSpace: "Digital Marketing" },
  { slug: "high-authority-community-posting-platform", label: "High Authority Community Posting Platform", parentSpace: "Digital Marketing" },
  { slug: "best-free-links-for-new-website", label: "Best Free Links for New Website", parentSpace: "Digital Marketing" },
  { slug: "contextual-backlink-submission-sites", label: "Contextual Backlink Submission Sites", parentSpace: "Digital Marketing" },
  { slug: "guest-blogging-opportunities", label: "Guest Blogging Opportunities", parentSpace: "Digital Marketing" },
  { slug: "forum-link-building-sites-free", label: "Forum Link Building Sites Free", parentSpace: "Digital Marketing" },
  { slug: "how-to-get-dofollow-links-from-forums", label: "How to Get Dofollow Links from Forums", parentSpace: "Digital Marketing" },
  { slug: "best-seo-forums for-link-drops", label: "Best SEO Forums for Link Drops", parentSpace: "Digital Marketing" },
  { slug: "free-profile-creation-sites-with-links", label: "Free Profile Creation Sites with Links", parentSpace: "Digital Marketing" },
  { slug: "discussion-board-backlinks-instant-approval", label: "Discussion Board Backlinks Instant Approval", parentSpace: "Digital Marketing" },
  { slug: "active-communities-for-off-page-seo", label: "Active Communities for Off Page SEO", parentSpace: "Digital Marketing" },
  { slug: "how-to-build-signature-links-on-forums", label: "How to Build Signature Links on Forums", parentSpace: "Digital Marketing" },
  { slug: "high-trust-community-posting-platforms", label: "High Trust Community Posting Platforms", parentSpace: "Digital Marketing" },
  { slug: "free-contextual-link-wheels-forum", label: "Free Contextual Link Wheels Forum", parentSpace: "Digital Marketing" },
  { slug: "dofollow-bio-link-platforms", label: "Dofollow Bio Link Platforms", parentSpace: "Digital Marketing" },
  { slug: "free-alternative-to-paid-guest-post-networks", label: "Free Alternative to Paid Guest Post Networks", parentSpace: "Digital Marketing" },
  { slug: "where-to-post-articles for-backlinks-free", label: "Where to Post Articles for Backlinks Free", parentSpace: "Digital Marketing" },
  { slug: "free-automated-article-distribution-platforms", label: "Free Automated Article Distribution Platforms", parentSpace: "Digital Marketing" },
  { slug: "how-to-pass-links-using-web-2-0-profiles", label: "How to Pass Links Using Web 2.0 Profiles", parentSpace: "Digital Marketing" },
  { slug: "organic-traffic-safe-backlink-websites", label: "Organic Traffic Safe Backlink Websites", parentSpace: "Digital Marketing" },
  { slug: "how-to-find-niche-edits-platforms", label: "How to Find Niche Edits Platforms", parentSpace: "Digital Marketing" },
  { slug: "free-link-insertions-community-sites", label: "Free Link Insertions Community Sites", parentSpace: "Digital Marketing" },
  { slug: "instant-live-link-posting-sites", label: "Instant Live Link Posting Sites", parentSpace: "Digital Marketing" },
  { slug: "high-metrics-seo-footprints-list", label: "High Metrics SEO Footprints List", parentSpace: "Digital Marketing" },
  { slug: "unlocked-blog-posting-platforms-free", label: "Unlocked Blog Posting Platforms Free", parentSpace: "Digital Marketing" },
  { slug: "free-backlink-checker-websites-open-list", label: "Free Backlink Checker Websites Open List", parentSpace: "Digital Marketing" },
  { slug: "high-pr-profile-submission-sites-list-free", label: "High PR Profile Submission Sites List Free", parentSpace: "Digital Marketing" },
  { slug: "dofollow-links-from-community-sites-list", label: "Dofollow Links from Community Sites List", parentSpace: "Digital Marketing" },
  { slug: "instant-approval-blog-commenting-sites-list", label: "Instant Approval Blog Commenting Sites List", parentSpace: "Digital Marketing" },
  { slug: "best-web-2-0-creation-platforms-free", label: "Best Web 2.0 Creation Platforms Free", parentSpace: "Digital Marketing" },
  { slug: "free-citation-sites-list-for-seo", label: "Free Citation Sites List for SEO", parentSpace: "Digital Marketing" },
  { slug: "instant-live-link-posting-websites", label: "Instant Live Link Posting Websites", parentSpace: "Digital Marketing" },
  { slug: "free-high-metrics-backlink-source-list", label: "Free High Metrics Backlink Source List", parentSpace: "Digital Marketing" },
  { slug: "how-to-build-foundational-backlinks-for-free", label: "How to Build Foundational Backlinks for Free", parentSpace: "Digital Marketing" },
  { slug: "free-press-release-submission-sites-list", label: "Free Press Release Submission Sites List", parentSpace: "Digital Marketing" },
  { slug: "free-edu-and-gov-backlinks-site-list", label: "Free Edu and Gov Backlinks Site List", parentSpace: "Digital Marketing" },
  { slug: "dofollow-link-submission-without-registration", label: "Dofollow Link Submission Without Registration", parentSpace: "Digital Marketing" },
  { slug: "free-directory-submission-sites-list-high-da", label: "Free Directory Submission Sites List High DA", parentSpace: "Digital Marketing" },
  { slug: "instant-approval-guest-blogging-sites", label: "Instant Approval Guest Blogging Sites", parentSpace: "Digital Marketing" },
  { slug: "free-article-directory-sites-list-dofollow", label: "Free Article Directory Sites List Dofollow", parentSpace: "Digital Marketing" },
  { slug: "high-domain-authority-free-link-platforms", label: "High Domain Authority Free Link Platforms", parentSpace: "Digital Marketing" },
  { slug: "free-list-of-dofollow-backlink-websites", label: "Free List of Dofollow Backlink Websites", parentSpace: "Digital Marketing" },
  { slug: "where-can-i-drop-links-for-seo-free", label: "Where Can I Drop Links for SEO Free", parentSpace: "Digital Marketing" },
  { slug: "best-free-off-page-seo-sites-list", label: "Best Free Off Page SEO Sites List", parentSpace: "Digital Marketing" },
  { slug: "instant-indexing-web-2-0-list-free", label: "Instant Indexing Web 2.0 List Free", parentSpace: "Digital Marketing" },
  { slug: "organic-traffic-driver-free-backlink-list", label: "Organic Traffic Driver Free Backlink List", parentSpace: "Digital Marketing" },
  { slug: "free-bookmarking-sites-list-high-authority", label: "Free Bookmarking Sites List High Authority", parentSpace: "Digital Marketing" },
  { slug: "dofollow-forum-profile-backlinks-list", label: "Dofollow Forum Profile Backlinks List", parentSpace: "Digital Marketing" },
  { slug: "free-article-submission-sites-list-without-account", label: "Free Article Submission Sites List Without Account", parentSpace: "Digital Marketing" },
  { slug: "best-free-digital-marketing-link-dropping-sites", label: "Best Free Digital Marketing Link Dropping Sites", parentSpace: "Digital Marketing" },

  // === STARTUPS & BUSINESS SPACE ===
  { slug: "become-a-contributor-business", label: "\"Become a contributor\" Business", parentSpace: "Startups & Business" },
  { slug: "submit-an-article-finance", label: "\"Submit an article\" Finance", parentSpace: "Startups & Business" },
  { slug: "editorial-guidelines-startup-news", label: "\"Editorial guidelines\" Startup News", parentSpace: "Startups & Business" },
  { slug: "community-contributor-wanted-career", label: "\"Community contributor wanted\" Career", parentSpace: "Startups & Business" },

  // === GENERAL TECH SPACE ===
  { slug: "write-for-us-guest-post-seo", label: "\"Write for us\" Guest Post SEO", parentSpace: "General Tech" },
  { slug: "submit-guest-post-technology", label: "Intitle:\"Submit guest post\" Technology", parentSpace: "General Tech" },
  { slug: "guest-author-guidelines-marketing", label: "Inurl:guest-author-guidelines Marketing", parentSpace: "General Tech" },
  { slug: "contribute-to-our-site-design", label: "Intitle:\"Contribute to our site\" Design", parentSpace: "General Tech" },

  // === HEALTH - FITNESS - BEAUTY SPACE ===
  { slug: "write-for-us-health-fitness", label: "Intitle:\"Write for us\" Health Fitness", parentSpace: "Health - Fitness - Beauty" },

  // === OTHERS / SPECIFIC NICHES MAPS ===
  { slug: "guest-post-guidelines-gaming", label: "\"Guest post guidelines\" Gaming", parentSpace: "Others" },
  { slug: "submit-post-travel-blog", label: "Inurl:submit-post Travel Blog", parentSpace: "Others" },
  { slug: "accepting-guest-submissions-lifestyle", label: "\"Accepting guest submissions\" Lifestyle", parentSpace: "Others" },
  { slug: "guest-blogging-opportunities-food", label: "\"Guest blogging opportunities\" Food", parentSpace: "Others" },
  { slug: "write-for-us-automotive", label: "Inurl:write-for-us Automotive", parentSpace: "Others" },
  { slug: "free-guest-article-submission-home-decor", label: "\"Free guest article submission\" Home Decor", parentSpace: "Others" }
];
